
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'IDENTIFIER PIPE REDIRECT_IN REDIRECT_OUT SEMICOLONprogram : command_listcommand_list : command_list SEMICOLON pipeline\n                    | pipelinepipeline : pipeline PIPE command\n                | commandcommand : IDENTIFIER redirect_list\n               | IDENTIFIERredirect_list : redirect_list REDIRECT_IN IDENTIFIER\n                     | redirect_list REDIRECT_OUT IDENTIFIER\n                     | REDIRECT_IN IDENTIFIER\n                     | REDIRECT_OUT IDENTIFIER'
    
_lr_action_items = {'IDENTIFIER':([0,6,7,9,10,13,14,],[5,5,5,15,16,17,18,]),'$end':([1,2,3,4,5,8,11,12,15,16,17,18,],[0,-1,-3,-5,-7,-6,-2,-4,-10,-11,-8,-9,]),'SEMICOLON':([2,3,4,5,8,11,12,15,16,17,18,],[6,-3,-5,-7,-6,-2,-4,-10,-11,-8,-9,]),'PIPE':([3,4,5,8,11,12,15,16,17,18,],[7,-5,-7,-6,7,-4,-10,-11,-8,-9,]),'REDIRECT_IN':([5,8,15,16,17,18,],[9,13,-10,-11,-8,-9,]),'REDIRECT_OUT':([5,8,15,16,17,18,],[10,14,-10,-11,-8,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'command_list':([0,],[2,]),'pipeline':([0,6,],[3,11,]),'command':([0,6,7,],[4,4,12,]),'redirect_list':([5,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> command_list','program',1,'p_program','parser.py',19),
  ('command_list -> command_list SEMICOLON pipeline','command_list',3,'p_command_list','parser.py',23),
  ('command_list -> pipeline','command_list',1,'p_command_list','parser.py',24),
  ('pipeline -> pipeline PIPE command','pipeline',3,'p_pipeline','parser.py',31),
  ('pipeline -> command','pipeline',1,'p_pipeline','parser.py',32),
  ('command -> IDENTIFIER redirect_list','command',2,'p_command','parser.py',39),
  ('command -> IDENTIFIER','command',1,'p_command','parser.py',40),
  ('redirect_list -> redirect_list REDIRECT_IN IDENTIFIER','redirect_list',3,'p_redirect_list','parser.py',47),
  ('redirect_list -> redirect_list REDIRECT_OUT IDENTIFIER','redirect_list',3,'p_redirect_list','parser.py',48),
  ('redirect_list -> REDIRECT_IN IDENTIFIER','redirect_list',2,'p_redirect_list','parser.py',49),
  ('redirect_list -> REDIRECT_OUT IDENTIFIER','redirect_list',2,'p_redirect_list','parser.py',50),
]
